apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: rest-service
images:
  - name: apps/rest-service
    newName: localhost:5000/apps/rest-service
resources:
  - deployment.yaml
namePrefix: rest-service
